###
GET http://localhost:5000/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdmMzU3NjZlMjlkZjQ3YmU1MjNhNzIiLCJpYXQiOjE3MTk2MTI3OTYsImV4cCI6MTcxOTYxNjM5Nn0.HFDtuyu9cR9CAyUfg7Z5oFNEB9_A2rgL0Qdyb-PfIvs

###
POST http://localhost:5000/api/register
Content-Type: application/json

{
    "username": "Naruto",
    "password": "hejsan123",
    "confirmPassword": "hejsan123"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username": "Naruto",
    "password": "hejsan123"
}
